# Generated by Django 6.0 on 2026-01-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('stars', models.IntegerField(verbose_name='Estrelas')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='provider.provider', verbose_name='Prestador de Serviço')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='condominium.condominiumresident', verbose_name='Morador')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'ratings',
            },
        ),
    ]
