# Generated by Django 6.0 on 2026-01-04 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='address.address', verbose_name='Endereço')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='categories.category', verbose_name='Categoria')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'db_table': 'providers',
            },
        ),
    ]
