# Generated by Django 6.0 on 2026-01-09 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('street', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'db_table': 'condominiuns',
            },
        ),
        migrations.CreateModel(
            name='CondominiumProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_providers', to='condominium.condominium', verbose_name='Condomínio')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_providers', to='provider.provider', verbose_name='Prestador de Serviço')),
            ],
            options={
                'verbose_name': 'Prestador de Serviço',
                'verbose_name_plural': 'Prestadores de Serviços',
                'db_table': 'condominium_providers',
            },
        ),
        migrations.CreateModel(
            name='CondominiumResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('apartment', models.IntegerField(verbose_name='Apartamento')),
                ('block', models.CharField(max_length=50, verbose_name='Bloco')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_residents', to='condominium.condominium', verbose_name='Condomínio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_residents', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'db_table': 'condominium_residents',
            },
        ),
    ]
